export const theme={
    primary: "#FF4E54",
    secondary: "#FF8242",
    success: "#07CB6E",
    warning: "#F3B664",
    cardBorder: "#E49393",
    cardTitle: "#060047",
    cardText: "#1640D6",
    cardButtonBg: "#E90064",
    cardButtonHoverBg: "#FF5F9E",
    textLink: "#E26EE5",
    iconAfterLink: "#ccc",
    buttonOutlinedSecondaryBorder: "#E26EE5",
    buttonOutlinedSecondaryBgHover: "#E26EE5",
    buttonOutlinedSecondaryTextHover: "#fff",
    badgeBg: "#FF3D00",
    badgeText: "#fff",
    white: "#f6f9fc",
    black: "#000"
};
